services:
  authentication-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: auth-service/.env
    ports:
      - "3001:3001"
    volumes:
      - sqlite-data:/data
    networks:
      - app-network

volumes:
  sqlite-data:

networks:
  app-network:
    driver: bridge